package com.csy.model;

import java.io.Serializable;
import java.util.Date;

public class Blogroll implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.title
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.image_url
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.link
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.status
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.create_tm
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Date createTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.creator
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.modify_tm
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Date modifyTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.modifior
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String modifior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogroll.sort
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.id
     *
     * @return the value of blogroll.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.id
     *
     * @param id the value for blogroll.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.title
     *
     * @return the value of blogroll.title
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.title
     *
     * @param title the value for blogroll.title
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.image_url
     *
     * @return the value of blogroll.image_url
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.image_url
     *
     * @param imageUrl the value for blogroll.image_url
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.link
     *
     * @return the value of blogroll.link
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.link
     *
     * @param link the value for blogroll.link
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.status
     *
     * @return the value of blogroll.status
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.status
     *
     * @param status the value for blogroll.status
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.create_tm
     *
     * @return the value of blogroll.create_tm
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.create_tm
     *
     * @param createTm the value for blogroll.create_tm
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.creator
     *
     * @return the value of blogroll.creator
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.creator
     *
     * @param creator the value for blogroll.creator
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.modify_tm
     *
     * @return the value of blogroll.modify_tm
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Date getModifyTm() {
        return modifyTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.modify_tm
     *
     * @param modifyTm the value for blogroll.modify_tm
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setModifyTm(Date modifyTm) {
        this.modifyTm = modifyTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.modifior
     *
     * @return the value of blogroll.modifior
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getModifior() {
        return modifior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.modifior
     *
     * @param modifior the value for blogroll.modifior
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setModifior(String modifior) {
        this.modifior = modifior == null ? null : modifior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogroll.sort
     *
     * @return the value of blogroll.sort
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogroll.sort
     *
     * @param sort the value for blogroll.sort
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}