package com.csy.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommodityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public CommodityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIsNull() {
            addCriterion("commodity_id is null");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIsNotNull() {
            addCriterion("commodity_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityIdEqualTo(Long value) {
            addCriterion("commodity_id =", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotEqualTo(Long value) {
            addCriterion("commodity_id <>", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdGreaterThan(Long value) {
            addCriterion("commodity_id >", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("commodity_id >=", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLessThan(Long value) {
            addCriterion("commodity_id <", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdLessThanOrEqualTo(Long value) {
            addCriterion("commodity_id <=", value, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdIn(List<Long> values) {
            addCriterion("commodity_id in", values, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotIn(List<Long> values) {
            addCriterion("commodity_id not in", values, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdBetween(Long value1, Long value2) {
            addCriterion("commodity_id between", value1, value2, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityIdNotBetween(Long value1, Long value2) {
            addCriterion("commodity_id not between", value1, value2, "commodityId");
            return (Criteria) this;
        }

        public Criteria andCommodityNameIsNull() {
            addCriterion("commodity_name is null");
            return (Criteria) this;
        }

        public Criteria andCommodityNameIsNotNull() {
            addCriterion("commodity_name is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityNameEqualTo(String value) {
            addCriterion("commodity_name =", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotEqualTo(String value) {
            addCriterion("commodity_name <>", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameGreaterThan(String value) {
            addCriterion("commodity_name >", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_name >=", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameLessThan(String value) {
            addCriterion("commodity_name <", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameLessThanOrEqualTo(String value) {
            addCriterion("commodity_name <=", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameLike(String value) {
            addCriterion("commodity_name like", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotLike(String value) {
            addCriterion("commodity_name not like", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameIn(List<String> values) {
            addCriterion("commodity_name in", values, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotIn(List<String> values) {
            addCriterion("commodity_name not in", values, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameBetween(String value1, String value2) {
            addCriterion("commodity_name between", value1, value2, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotBetween(String value1, String value2) {
            addCriterion("commodity_name not between", value1, value2, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityPicIsNull() {
            addCriterion("commodity_pic is null");
            return (Criteria) this;
        }

        public Criteria andCommodityPicIsNotNull() {
            addCriterion("commodity_pic is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityPicEqualTo(String value) {
            addCriterion("commodity_pic =", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicNotEqualTo(String value) {
            addCriterion("commodity_pic <>", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicGreaterThan(String value) {
            addCriterion("commodity_pic >", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_pic >=", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicLessThan(String value) {
            addCriterion("commodity_pic <", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicLessThanOrEqualTo(String value) {
            addCriterion("commodity_pic <=", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicLike(String value) {
            addCriterion("commodity_pic like", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicNotLike(String value) {
            addCriterion("commodity_pic not like", value, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicIn(List<String> values) {
            addCriterion("commodity_pic in", values, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicNotIn(List<String> values) {
            addCriterion("commodity_pic not in", values, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicBetween(String value1, String value2) {
            addCriterion("commodity_pic between", value1, value2, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityPicNotBetween(String value1, String value2) {
            addCriterion("commodity_pic not between", value1, value2, "commodityPic");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailIsNull() {
            addCriterion("commodity_detail is null");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailIsNotNull() {
            addCriterion("commodity_detail is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailEqualTo(String value) {
            addCriterion("commodity_detail =", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailNotEqualTo(String value) {
            addCriterion("commodity_detail <>", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailGreaterThan(String value) {
            addCriterion("commodity_detail >", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_detail >=", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailLessThan(String value) {
            addCriterion("commodity_detail <", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailLessThanOrEqualTo(String value) {
            addCriterion("commodity_detail <=", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailLike(String value) {
            addCriterion("commodity_detail like", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailNotLike(String value) {
            addCriterion("commodity_detail not like", value, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailIn(List<String> values) {
            addCriterion("commodity_detail in", values, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailNotIn(List<String> values) {
            addCriterion("commodity_detail not in", values, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailBetween(String value1, String value2) {
            addCriterion("commodity_detail between", value1, value2, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityDetailNotBetween(String value1, String value2) {
            addCriterion("commodity_detail not between", value1, value2, "commodityDetail");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkIsNull() {
            addCriterion("commodity_tbk is null");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkIsNotNull() {
            addCriterion("commodity_tbk is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkEqualTo(String value) {
            addCriterion("commodity_tbk =", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkNotEqualTo(String value) {
            addCriterion("commodity_tbk <>", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkGreaterThan(String value) {
            addCriterion("commodity_tbk >", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_tbk >=", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkLessThan(String value) {
            addCriterion("commodity_tbk <", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkLessThanOrEqualTo(String value) {
            addCriterion("commodity_tbk <=", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkLike(String value) {
            addCriterion("commodity_tbk like", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkNotLike(String value) {
            addCriterion("commodity_tbk not like", value, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkIn(List<String> values) {
            addCriterion("commodity_tbk in", values, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkNotIn(List<String> values) {
            addCriterion("commodity_tbk not in", values, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkBetween(String value1, String value2) {
            addCriterion("commodity_tbk between", value1, value2, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityTbkNotBetween(String value1, String value2) {
            addCriterion("commodity_tbk not between", value1, value2, "commodityTbk");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryIsNull() {
            addCriterion("commodity_category is null");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryIsNotNull() {
            addCriterion("commodity_category is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryEqualTo(String value) {
            addCriterion("commodity_category =", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryNotEqualTo(String value) {
            addCriterion("commodity_category <>", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryGreaterThan(String value) {
            addCriterion("commodity_category >", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_category >=", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryLessThan(String value) {
            addCriterion("commodity_category <", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryLessThanOrEqualTo(String value) {
            addCriterion("commodity_category <=", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryLike(String value) {
            addCriterion("commodity_category like", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryNotLike(String value) {
            addCriterion("commodity_category not like", value, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryIn(List<String> values) {
            addCriterion("commodity_category in", values, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryNotIn(List<String> values) {
            addCriterion("commodity_category not in", values, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryBetween(String value1, String value2) {
            addCriterion("commodity_category between", value1, value2, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityCategoryNotBetween(String value1, String value2) {
            addCriterion("commodity_category not between", value1, value2, "commodityCategory");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceIsNull() {
            addCriterion("commodity_price is null");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceIsNotNull() {
            addCriterion("commodity_price is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceEqualTo(BigDecimal value) {
            addCriterion("commodity_price =", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceNotEqualTo(BigDecimal value) {
            addCriterion("commodity_price <>", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceGreaterThan(BigDecimal value) {
            addCriterion("commodity_price >", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("commodity_price >=", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceLessThan(BigDecimal value) {
            addCriterion("commodity_price <", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("commodity_price <=", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceIn(List<BigDecimal> values) {
            addCriterion("commodity_price in", values, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceNotIn(List<BigDecimal> values) {
            addCriterion("commodity_price not in", values, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commodity_price between", value1, value2, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("commodity_price not between", value1, value2, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesIsNull() {
            addCriterion("commodity_sales is null");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesIsNotNull() {
            addCriterion("commodity_sales is not null");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesEqualTo(Integer value) {
            addCriterion("commodity_sales =", value, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesNotEqualTo(Integer value) {
            addCriterion("commodity_sales <>", value, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesGreaterThan(Integer value) {
            addCriterion("commodity_sales >", value, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("commodity_sales >=", value, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesLessThan(Integer value) {
            addCriterion("commodity_sales <", value, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesLessThanOrEqualTo(Integer value) {
            addCriterion("commodity_sales <=", value, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesIn(List<Integer> values) {
            addCriterion("commodity_sales in", values, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesNotIn(List<Integer> values) {
            addCriterion("commodity_sales not in", values, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesBetween(Integer value1, Integer value2) {
            addCriterion("commodity_sales between", value1, value2, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommoditySalesNotBetween(Integer value1, Integer value2) {
            addCriterion("commodity_sales not between", value1, value2, "commoditySales");
            return (Criteria) this;
        }

        public Criteria andCommodityRateIsNull() {
            addCriterion("commodity_rate is null");
            return (Criteria) this;
        }

        public Criteria andCommodityRateIsNotNull() {
            addCriterion("commodity_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityRateEqualTo(Double value) {
            addCriterion("commodity_rate =", value, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateNotEqualTo(Double value) {
            addCriterion("commodity_rate <>", value, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateGreaterThan(Double value) {
            addCriterion("commodity_rate >", value, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateGreaterThanOrEqualTo(Double value) {
            addCriterion("commodity_rate >=", value, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateLessThan(Double value) {
            addCriterion("commodity_rate <", value, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateLessThanOrEqualTo(Double value) {
            addCriterion("commodity_rate <=", value, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateIn(List<Double> values) {
            addCriterion("commodity_rate in", values, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateNotIn(List<Double> values) {
            addCriterion("commodity_rate not in", values, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateBetween(Double value1, Double value2) {
            addCriterion("commodity_rate between", value1, value2, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andCommodityRateNotBetween(Double value1, Double value2) {
            addCriterion("commodity_rate not between", value1, value2, "commodityRate");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(Long value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(Long value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(Long value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(Long value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(Long value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<Long> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<Long> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(Long value1, Long value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(Long value1, Long value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerNameIsNull() {
            addCriterion("seller_name is null");
            return (Criteria) this;
        }

        public Criteria andSellerNameIsNotNull() {
            addCriterion("seller_name is not null");
            return (Criteria) this;
        }

        public Criteria andSellerNameEqualTo(String value) {
            addCriterion("seller_name =", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameNotEqualTo(String value) {
            addCriterion("seller_name <>", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameGreaterThan(String value) {
            addCriterion("seller_name >", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameGreaterThanOrEqualTo(String value) {
            addCriterion("seller_name >=", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameLessThan(String value) {
            addCriterion("seller_name <", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameLessThanOrEqualTo(String value) {
            addCriterion("seller_name <=", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameLike(String value) {
            addCriterion("seller_name like", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameNotLike(String value) {
            addCriterion("seller_name not like", value, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameIn(List<String> values) {
            addCriterion("seller_name in", values, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameNotIn(List<String> values) {
            addCriterion("seller_name not in", values, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameBetween(String value1, String value2) {
            addCriterion("seller_name between", value1, value2, "sellerName");
            return (Criteria) this;
        }

        public Criteria andSellerNameNotBetween(String value1, String value2) {
            addCriterion("seller_name not between", value1, value2, "sellerName");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopTypeIsNull() {
            addCriterion("shop_type is null");
            return (Criteria) this;
        }

        public Criteria andShopTypeIsNotNull() {
            addCriterion("shop_type is not null");
            return (Criteria) this;
        }

        public Criteria andShopTypeEqualTo(Byte value) {
            addCriterion("shop_type =", value, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeNotEqualTo(Byte value) {
            addCriterion("shop_type <>", value, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeGreaterThan(Byte value) {
            addCriterion("shop_type >", value, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("shop_type >=", value, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeLessThan(Byte value) {
            addCriterion("shop_type <", value, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeLessThanOrEqualTo(Byte value) {
            addCriterion("shop_type <=", value, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeIn(List<Byte> values) {
            addCriterion("shop_type in", values, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeNotIn(List<Byte> values) {
            addCriterion("shop_type not in", values, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeBetween(Byte value1, Byte value2) {
            addCriterion("shop_type between", value1, value2, "shopType");
            return (Criteria) this;
        }

        public Criteria andShopTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("shop_type not between", value1, value2, "shopType");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponIdEqualTo(String value) {
            addCriterion("coupon_id =", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotEqualTo(String value) {
            addCriterion("coupon_id <>", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThan(String value) {
            addCriterion("coupon_id >", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_id >=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThan(String value) {
            addCriterion("coupon_id <", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThanOrEqualTo(String value) {
            addCriterion("coupon_id <=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLike(String value) {
            addCriterion("coupon_id like", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotLike(String value) {
            addCriterion("coupon_id not like", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIn(List<String> values) {
            addCriterion("coupon_id in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotIn(List<String> values) {
            addCriterion("coupon_id not in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdBetween(String value1, String value2) {
            addCriterion("coupon_id between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotBetween(String value1, String value2) {
            addCriterion("coupon_id not between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponNumIsNull() {
            addCriterion("coupon_num is null");
            return (Criteria) this;
        }

        public Criteria andCouponNumIsNotNull() {
            addCriterion("coupon_num is not null");
            return (Criteria) this;
        }

        public Criteria andCouponNumEqualTo(Integer value) {
            addCriterion("coupon_num =", value, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumNotEqualTo(Integer value) {
            addCriterion("coupon_num <>", value, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumGreaterThan(Integer value) {
            addCriterion("coupon_num >", value, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon_num >=", value, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumLessThan(Integer value) {
            addCriterion("coupon_num <", value, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumLessThanOrEqualTo(Integer value) {
            addCriterion("coupon_num <=", value, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumIn(List<Integer> values) {
            addCriterion("coupon_num in", values, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumNotIn(List<Integer> values) {
            addCriterion("coupon_num not in", values, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumBetween(Integer value1, Integer value2) {
            addCriterion("coupon_num between", value1, value2, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponNumNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon_num not between", value1, value2, "couponNum");
            return (Criteria) this;
        }

        public Criteria andCouponResidueIsNull() {
            addCriterion("coupon_residue is null");
            return (Criteria) this;
        }

        public Criteria andCouponResidueIsNotNull() {
            addCriterion("coupon_residue is not null");
            return (Criteria) this;
        }

        public Criteria andCouponResidueEqualTo(Integer value) {
            addCriterion("coupon_residue =", value, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueNotEqualTo(Integer value) {
            addCriterion("coupon_residue <>", value, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueGreaterThan(Integer value) {
            addCriterion("coupon_residue >", value, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon_residue >=", value, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueLessThan(Integer value) {
            addCriterion("coupon_residue <", value, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueLessThanOrEqualTo(Integer value) {
            addCriterion("coupon_residue <=", value, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueIn(List<Integer> values) {
            addCriterion("coupon_residue in", values, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueNotIn(List<Integer> values) {
            addCriterion("coupon_residue not in", values, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueBetween(Integer value1, Integer value2) {
            addCriterion("coupon_residue between", value1, value2, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponResidueNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon_residue not between", value1, value2, "couponResidue");
            return (Criteria) this;
        }

        public Criteria andCouponDetailIsNull() {
            addCriterion("coupon_detail is null");
            return (Criteria) this;
        }

        public Criteria andCouponDetailIsNotNull() {
            addCriterion("coupon_detail is not null");
            return (Criteria) this;
        }

        public Criteria andCouponDetailEqualTo(String value) {
            addCriterion("coupon_detail =", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailNotEqualTo(String value) {
            addCriterion("coupon_detail <>", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailGreaterThan(String value) {
            addCriterion("coupon_detail >", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_detail >=", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailLessThan(String value) {
            addCriterion("coupon_detail <", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailLessThanOrEqualTo(String value) {
            addCriterion("coupon_detail <=", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailLike(String value) {
            addCriterion("coupon_detail like", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailNotLike(String value) {
            addCriterion("coupon_detail not like", value, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailIn(List<String> values) {
            addCriterion("coupon_detail in", values, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailNotIn(List<String> values) {
            addCriterion("coupon_detail not in", values, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailBetween(String value1, String value2) {
            addCriterion("coupon_detail between", value1, value2, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponDetailNotBetween(String value1, String value2) {
            addCriterion("coupon_detail not between", value1, value2, "couponDetail");
            return (Criteria) this;
        }

        public Criteria andCouponStartIsNull() {
            addCriterion("coupon_start is null");
            return (Criteria) this;
        }

        public Criteria andCouponStartIsNotNull() {
            addCriterion("coupon_start is not null");
            return (Criteria) this;
        }

        public Criteria andCouponStartEqualTo(Date value) {
            addCriterion("coupon_start =", value, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartNotEqualTo(Date value) {
            addCriterion("coupon_start <>", value, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartGreaterThan(Date value) {
            addCriterion("coupon_start >", value, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartGreaterThanOrEqualTo(Date value) {
            addCriterion("coupon_start >=", value, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartLessThan(Date value) {
            addCriterion("coupon_start <", value, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartLessThanOrEqualTo(Date value) {
            addCriterion("coupon_start <=", value, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartIn(List<Date> values) {
            addCriterion("coupon_start in", values, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartNotIn(List<Date> values) {
            addCriterion("coupon_start not in", values, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartBetween(Date value1, Date value2) {
            addCriterion("coupon_start between", value1, value2, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponStartNotBetween(Date value1, Date value2) {
            addCriterion("coupon_start not between", value1, value2, "couponStart");
            return (Criteria) this;
        }

        public Criteria andCouponEndIsNull() {
            addCriterion("coupon_end is null");
            return (Criteria) this;
        }

        public Criteria andCouponEndIsNotNull() {
            addCriterion("coupon_end is not null");
            return (Criteria) this;
        }

        public Criteria andCouponEndEqualTo(Date value) {
            addCriterion("coupon_end =", value, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndNotEqualTo(Date value) {
            addCriterion("coupon_end <>", value, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndGreaterThan(Date value) {
            addCriterion("coupon_end >", value, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndGreaterThanOrEqualTo(Date value) {
            addCriterion("coupon_end >=", value, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndLessThan(Date value) {
            addCriterion("coupon_end <", value, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndLessThanOrEqualTo(Date value) {
            addCriterion("coupon_end <=", value, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndIn(List<Date> values) {
            addCriterion("coupon_end in", values, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndNotIn(List<Date> values) {
            addCriterion("coupon_end not in", values, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndBetween(Date value1, Date value2) {
            addCriterion("coupon_end between", value1, value2, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponEndNotBetween(Date value1, Date value2) {
            addCriterion("coupon_end not between", value1, value2, "couponEnd");
            return (Criteria) this;
        }

        public Criteria andCouponLinkIsNull() {
            addCriterion("coupon_link is null");
            return (Criteria) this;
        }

        public Criteria andCouponLinkIsNotNull() {
            addCriterion("coupon_link is not null");
            return (Criteria) this;
        }

        public Criteria andCouponLinkEqualTo(String value) {
            addCriterion("coupon_link =", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkNotEqualTo(String value) {
            addCriterion("coupon_link <>", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkGreaterThan(String value) {
            addCriterion("coupon_link >", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_link >=", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkLessThan(String value) {
            addCriterion("coupon_link <", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkLessThanOrEqualTo(String value) {
            addCriterion("coupon_link <=", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkLike(String value) {
            addCriterion("coupon_link like", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkNotLike(String value) {
            addCriterion("coupon_link not like", value, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkIn(List<String> values) {
            addCriterion("coupon_link in", values, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkNotIn(List<String> values) {
            addCriterion("coupon_link not in", values, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkBetween(String value1, String value2) {
            addCriterion("coupon_link between", value1, value2, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCouponLinkNotBetween(String value1, String value2) {
            addCriterion("coupon_link not between", value1, value2, "couponLink");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIsNull() {
            addCriterion("commodity_type is null");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIsNotNull() {
            addCriterion("commodity_type is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeEqualTo(Byte value) {
            addCriterion("commodity_type =", value, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeNotEqualTo(Byte value) {
            addCriterion("commodity_type <>", value, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeGreaterThan(Byte value) {
            addCriterion("commodity_type >", value, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("commodity_type >=", value, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeLessThan(Byte value) {
            addCriterion("commodity_type <", value, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeLessThanOrEqualTo(Byte value) {
            addCriterion("commodity_type <=", value, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeIn(List<Byte> values) {
            addCriterion("commodity_type in", values, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeNotIn(List<Byte> values) {
            addCriterion("commodity_type not in", values, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeBetween(Byte value1, Byte value2) {
            addCriterion("commodity_type between", value1, value2, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("commodity_type not between", value1, value2, "commodityType");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusIsNull() {
            addCriterion("commodity_status is null");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusIsNotNull() {
            addCriterion("commodity_status is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusEqualTo(Byte value) {
            addCriterion("commodity_status =", value, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusNotEqualTo(Byte value) {
            addCriterion("commodity_status <>", value, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusGreaterThan(Byte value) {
            addCriterion("commodity_status >", value, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("commodity_status >=", value, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusLessThan(Byte value) {
            addCriterion("commodity_status <", value, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusLessThanOrEqualTo(Byte value) {
            addCriterion("commodity_status <=", value, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusIn(List<Byte> values) {
            addCriterion("commodity_status in", values, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusNotIn(List<Byte> values) {
            addCriterion("commodity_status not in", values, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusBetween(Byte value1, Byte value2) {
            addCriterion("commodity_status between", value1, value2, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCommodityStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("commodity_status not between", value1, value2, "commodityStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTmIsNull() {
            addCriterion("create_tm is null");
            return (Criteria) this;
        }

        public Criteria andCreateTmIsNotNull() {
            addCriterion("create_tm is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTmEqualTo(Date value) {
            addCriterion("create_tm =", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmNotEqualTo(Date value) {
            addCriterion("create_tm <>", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmGreaterThan(Date value) {
            addCriterion("create_tm >", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmGreaterThanOrEqualTo(Date value) {
            addCriterion("create_tm >=", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmLessThan(Date value) {
            addCriterion("create_tm <", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmLessThanOrEqualTo(Date value) {
            addCriterion("create_tm <=", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmIn(List<Date> values) {
            addCriterion("create_tm in", values, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmNotIn(List<Date> values) {
            addCriterion("create_tm not in", values, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmBetween(Date value1, Date value2) {
            addCriterion("create_tm between", value1, value2, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmNotBetween(Date value1, Date value2) {
            addCriterion("create_tm not between", value1, value2, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifyTmIsNull() {
            addCriterion("modify_tm is null");
            return (Criteria) this;
        }

        public Criteria andModifyTmIsNotNull() {
            addCriterion("modify_tm is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTmEqualTo(Date value) {
            addCriterion("modify_tm =", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmNotEqualTo(Date value) {
            addCriterion("modify_tm <>", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmGreaterThan(Date value) {
            addCriterion("modify_tm >", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_tm >=", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmLessThan(Date value) {
            addCriterion("modify_tm <", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmLessThanOrEqualTo(Date value) {
            addCriterion("modify_tm <=", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmIn(List<Date> values) {
            addCriterion("modify_tm in", values, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmNotIn(List<Date> values) {
            addCriterion("modify_tm not in", values, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmBetween(Date value1, Date value2) {
            addCriterion("modify_tm between", value1, value2, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmNotBetween(Date value1, Date value2) {
            addCriterion("modify_tm not between", value1, value2, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifiorIsNull() {
            addCriterion("modifior is null");
            return (Criteria) this;
        }

        public Criteria andModifiorIsNotNull() {
            addCriterion("modifior is not null");
            return (Criteria) this;
        }

        public Criteria andModifiorEqualTo(String value) {
            addCriterion("modifior =", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotEqualTo(String value) {
            addCriterion("modifior <>", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorGreaterThan(String value) {
            addCriterion("modifior >", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorGreaterThanOrEqualTo(String value) {
            addCriterion("modifior >=", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorLessThan(String value) {
            addCriterion("modifior <", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorLessThanOrEqualTo(String value) {
            addCriterion("modifior <=", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorLike(String value) {
            addCriterion("modifior like", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotLike(String value) {
            addCriterion("modifior not like", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorIn(List<String> values) {
            addCriterion("modifior in", values, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotIn(List<String> values) {
            addCriterion("modifior not in", values, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorBetween(String value1, String value2) {
            addCriterion("modifior between", value1, value2, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotBetween(String value1, String value2) {
            addCriterion("modifior not between", value1, value2, "modifior");
            return (Criteria) this;
        }

        public Criteria andCouponPayIsNull() {
            addCriterion("coupon_pay is null");
            return (Criteria) this;
        }

        public Criteria andCouponPayIsNotNull() {
            addCriterion("coupon_pay is not null");
            return (Criteria) this;
        }

        public Criteria andCouponPayEqualTo(BigDecimal value) {
            addCriterion("coupon_pay =", value, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayNotEqualTo(BigDecimal value) {
            addCriterion("coupon_pay <>", value, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayGreaterThan(BigDecimal value) {
            addCriterion("coupon_pay >", value, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("coupon_pay >=", value, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayLessThan(BigDecimal value) {
            addCriterion("coupon_pay <", value, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("coupon_pay <=", value, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayIn(List<BigDecimal> values) {
            addCriterion("coupon_pay in", values, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayNotIn(List<BigDecimal> values) {
            addCriterion("coupon_pay not in", values, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coupon_pay between", value1, value2, "couponPay");
            return (Criteria) this;
        }

        public Criteria andCouponPayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coupon_pay not between", value1, value2, "couponPay");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 07 20:46:00 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commodity
     *
     * @mbg.generated Tue Mar 07 20:46:00 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}