package com.csy.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public MissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMissionTitleIsNull() {
            addCriterion("mission_title is null");
            return (Criteria) this;
        }

        public Criteria andMissionTitleIsNotNull() {
            addCriterion("mission_title is not null");
            return (Criteria) this;
        }

        public Criteria andMissionTitleEqualTo(String value) {
            addCriterion("mission_title =", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleNotEqualTo(String value) {
            addCriterion("mission_title <>", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleGreaterThan(String value) {
            addCriterion("mission_title >", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleGreaterThanOrEqualTo(String value) {
            addCriterion("mission_title >=", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleLessThan(String value) {
            addCriterion("mission_title <", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleLessThanOrEqualTo(String value) {
            addCriterion("mission_title <=", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleLike(String value) {
            addCriterion("mission_title like", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleNotLike(String value) {
            addCriterion("mission_title not like", value, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleIn(List<String> values) {
            addCriterion("mission_title in", values, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleNotIn(List<String> values) {
            addCriterion("mission_title not in", values, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleBetween(String value1, String value2) {
            addCriterion("mission_title between", value1, value2, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andMissionTitleNotBetween(String value1, String value2) {
            addCriterion("mission_title not between", value1, value2, "missionTitle");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Short value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Short value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Short value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Short value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Short value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Short value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Short> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Short> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Short value1, Short value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Short value1, Short value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andRealPriceIsNull() {
            addCriterion("real_price is null");
            return (Criteria) this;
        }

        public Criteria andRealPriceIsNotNull() {
            addCriterion("real_price is not null");
            return (Criteria) this;
        }

        public Criteria andRealPriceEqualTo(Short value) {
            addCriterion("real_price =", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotEqualTo(Short value) {
            addCriterion("real_price <>", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceGreaterThan(Short value) {
            addCriterion("real_price >", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceGreaterThanOrEqualTo(Short value) {
            addCriterion("real_price >=", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceLessThan(Short value) {
            addCriterion("real_price <", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceLessThanOrEqualTo(Short value) {
            addCriterion("real_price <=", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceIn(List<Short> values) {
            addCriterion("real_price in", values, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotIn(List<Short> values) {
            addCriterion("real_price not in", values, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceBetween(Short value1, Short value2) {
            addCriterion("real_price between", value1, value2, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotBetween(Short value1, Short value2) {
            addCriterion("real_price not between", value1, value2, "realPrice");
            return (Criteria) this;
        }

        public Criteria andPriceVipIsNull() {
            addCriterion("price_vip is null");
            return (Criteria) this;
        }

        public Criteria andPriceVipIsNotNull() {
            addCriterion("price_vip is not null");
            return (Criteria) this;
        }

        public Criteria andPriceVipEqualTo(Short value) {
            addCriterion("price_vip =", value, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipNotEqualTo(Short value) {
            addCriterion("price_vip <>", value, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipGreaterThan(Short value) {
            addCriterion("price_vip >", value, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipGreaterThanOrEqualTo(Short value) {
            addCriterion("price_vip >=", value, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipLessThan(Short value) {
            addCriterion("price_vip <", value, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipLessThanOrEqualTo(Short value) {
            addCriterion("price_vip <=", value, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipIn(List<Short> values) {
            addCriterion("price_vip in", values, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipNotIn(List<Short> values) {
            addCriterion("price_vip not in", values, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipBetween(Short value1, Short value2) {
            addCriterion("price_vip between", value1, value2, "priceVip");
            return (Criteria) this;
        }

        public Criteria andPriceVipNotBetween(Short value1, Short value2) {
            addCriterion("price_vip not between", value1, value2, "priceVip");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andBeginTmIsNull() {
            addCriterion("begin_tm is null");
            return (Criteria) this;
        }

        public Criteria andBeginTmIsNotNull() {
            addCriterion("begin_tm is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTmEqualTo(Date value) {
            addCriterion("begin_tm =", value, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmNotEqualTo(Date value) {
            addCriterion("begin_tm <>", value, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmGreaterThan(Date value) {
            addCriterion("begin_tm >", value, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_tm >=", value, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmLessThan(Date value) {
            addCriterion("begin_tm <", value, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmLessThanOrEqualTo(Date value) {
            addCriterion("begin_tm <=", value, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmIn(List<Date> values) {
            addCriterion("begin_tm in", values, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmNotIn(List<Date> values) {
            addCriterion("begin_tm not in", values, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmBetween(Date value1, Date value2) {
            addCriterion("begin_tm between", value1, value2, "beginTm");
            return (Criteria) this;
        }

        public Criteria andBeginTmNotBetween(Date value1, Date value2) {
            addCriterion("begin_tm not between", value1, value2, "beginTm");
            return (Criteria) this;
        }

        public Criteria andEndTmIsNull() {
            addCriterion("end_tm is null");
            return (Criteria) this;
        }

        public Criteria andEndTmIsNotNull() {
            addCriterion("end_tm is not null");
            return (Criteria) this;
        }

        public Criteria andEndTmEqualTo(Date value) {
            addCriterion("end_tm =", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmNotEqualTo(Date value) {
            addCriterion("end_tm <>", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmGreaterThan(Date value) {
            addCriterion("end_tm >", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmGreaterThanOrEqualTo(Date value) {
            addCriterion("end_tm >=", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmLessThan(Date value) {
            addCriterion("end_tm <", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmLessThanOrEqualTo(Date value) {
            addCriterion("end_tm <=", value, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmIn(List<Date> values) {
            addCriterion("end_tm in", values, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmNotIn(List<Date> values) {
            addCriterion("end_tm not in", values, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmBetween(Date value1, Date value2) {
            addCriterion("end_tm between", value1, value2, "endTm");
            return (Criteria) this;
        }

        public Criteria andEndTmNotBetween(Date value1, Date value2) {
            addCriterion("end_tm not between", value1, value2, "endTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmIsNull() {
            addCriterion("create_tm is null");
            return (Criteria) this;
        }

        public Criteria andCreateTmIsNotNull() {
            addCriterion("create_tm is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTmEqualTo(Date value) {
            addCriterion("create_tm =", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmNotEqualTo(Date value) {
            addCriterion("create_tm <>", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmGreaterThan(Date value) {
            addCriterion("create_tm >", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmGreaterThanOrEqualTo(Date value) {
            addCriterion("create_tm >=", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmLessThan(Date value) {
            addCriterion("create_tm <", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmLessThanOrEqualTo(Date value) {
            addCriterion("create_tm <=", value, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmIn(List<Date> values) {
            addCriterion("create_tm in", values, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmNotIn(List<Date> values) {
            addCriterion("create_tm not in", values, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmBetween(Date value1, Date value2) {
            addCriterion("create_tm between", value1, value2, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreateTmNotBetween(Date value1, Date value2) {
            addCriterion("create_tm not between", value1, value2, "createTm");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifyTmIsNull() {
            addCriterion("modify_tm is null");
            return (Criteria) this;
        }

        public Criteria andModifyTmIsNotNull() {
            addCriterion("modify_tm is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTmEqualTo(Date value) {
            addCriterion("modify_tm =", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmNotEqualTo(Date value) {
            addCriterion("modify_tm <>", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmGreaterThan(Date value) {
            addCriterion("modify_tm >", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_tm >=", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmLessThan(Date value) {
            addCriterion("modify_tm <", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmLessThanOrEqualTo(Date value) {
            addCriterion("modify_tm <=", value, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmIn(List<Date> values) {
            addCriterion("modify_tm in", values, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmNotIn(List<Date> values) {
            addCriterion("modify_tm not in", values, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmBetween(Date value1, Date value2) {
            addCriterion("modify_tm between", value1, value2, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifyTmNotBetween(Date value1, Date value2) {
            addCriterion("modify_tm not between", value1, value2, "modifyTm");
            return (Criteria) this;
        }

        public Criteria andModifiorIsNull() {
            addCriterion("modifior is null");
            return (Criteria) this;
        }

        public Criteria andModifiorIsNotNull() {
            addCriterion("modifior is not null");
            return (Criteria) this;
        }

        public Criteria andModifiorEqualTo(String value) {
            addCriterion("modifior =", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotEqualTo(String value) {
            addCriterion("modifior <>", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorGreaterThan(String value) {
            addCriterion("modifior >", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorGreaterThanOrEqualTo(String value) {
            addCriterion("modifior >=", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorLessThan(String value) {
            addCriterion("modifior <", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorLessThanOrEqualTo(String value) {
            addCriterion("modifior <=", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorLike(String value) {
            addCriterion("modifior like", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotLike(String value) {
            addCriterion("modifior not like", value, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorIn(List<String> values) {
            addCriterion("modifior in", values, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotIn(List<String> values) {
            addCriterion("modifior not in", values, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorBetween(String value1, String value2) {
            addCriterion("modifior between", value1, value2, "modifior");
            return (Criteria) this;
        }

        public Criteria andModifiorNotBetween(String value1, String value2) {
            addCriterion("modifior not between", value1, value2, "modifior");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalIsNull() {
            addCriterion("settlement_interval is null");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalIsNotNull() {
            addCriterion("settlement_interval is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalEqualTo(Integer value) {
            addCriterion("settlement_interval =", value, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalNotEqualTo(Integer value) {
            addCriterion("settlement_interval <>", value, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalGreaterThan(Integer value) {
            addCriterion("settlement_interval >", value, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("settlement_interval >=", value, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalLessThan(Integer value) {
            addCriterion("settlement_interval <", value, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("settlement_interval <=", value, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalIn(List<Integer> values) {
            addCriterion("settlement_interval in", values, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalNotIn(List<Integer> values) {
            addCriterion("settlement_interval not in", values, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalBetween(Integer value1, Integer value2) {
            addCriterion("settlement_interval between", value1, value2, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andSettlementIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("settlement_interval not between", value1, value2, "settlementInterval");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("image_url is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("image_url is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("image_url =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("image_url <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("image_url >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("image_url >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("image_url <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("image_url <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("image_url like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("image_url not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("image_url in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("image_url not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("image_url between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("image_url not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlIsNull() {
            addCriterion("thumbnail_url is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlIsNotNull() {
            addCriterion("thumbnail_url is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlEqualTo(String value) {
            addCriterion("thumbnail_url =", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlNotEqualTo(String value) {
            addCriterion("thumbnail_url <>", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlGreaterThan(String value) {
            addCriterion("thumbnail_url >", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail_url >=", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlLessThan(String value) {
            addCriterion("thumbnail_url <", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlLessThanOrEqualTo(String value) {
            addCriterion("thumbnail_url <=", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlLike(String value) {
            addCriterion("thumbnail_url like", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlNotLike(String value) {
            addCriterion("thumbnail_url not like", value, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlIn(List<String> values) {
            addCriterion("thumbnail_url in", values, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlNotIn(List<String> values) {
            addCriterion("thumbnail_url not in", values, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlBetween(String value1, String value2) {
            addCriterion("thumbnail_url between", value1, value2, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andThumbnailUrlNotBetween(String value1, String value2) {
            addCriterion("thumbnail_url not between", value1, value2, "thumbnailUrl");
            return (Criteria) this;
        }

        public Criteria andStarLevelIsNull() {
            addCriterion("star_level is null");
            return (Criteria) this;
        }

        public Criteria andStarLevelIsNotNull() {
            addCriterion("star_level is not null");
            return (Criteria) this;
        }

        public Criteria andStarLevelEqualTo(Integer value) {
            addCriterion("star_level =", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotEqualTo(Integer value) {
            addCriterion("star_level <>", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelGreaterThan(Integer value) {
            addCriterion("star_level >", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("star_level >=", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelLessThan(Integer value) {
            addCriterion("star_level <", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelLessThanOrEqualTo(Integer value) {
            addCriterion("star_level <=", value, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelIn(List<Integer> values) {
            addCriterion("star_level in", values, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotIn(List<Integer> values) {
            addCriterion("star_level not in", values, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelBetween(Integer value1, Integer value2) {
            addCriterion("star_level between", value1, value2, "starLevel");
            return (Criteria) this;
        }

        public Criteria andStarLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("star_level not between", value1, value2, "starLevel");
            return (Criteria) this;
        }

        public Criteria andIpChangeIsNull() {
            addCriterion("ip_change is null");
            return (Criteria) this;
        }

        public Criteria andIpChangeIsNotNull() {
            addCriterion("ip_change is not null");
            return (Criteria) this;
        }

        public Criteria andIpChangeEqualTo(Boolean value) {
            addCriterion("ip_change =", value, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeNotEqualTo(Boolean value) {
            addCriterion("ip_change <>", value, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeGreaterThan(Boolean value) {
            addCriterion("ip_change >", value, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ip_change >=", value, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeLessThan(Boolean value) {
            addCriterion("ip_change <", value, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeLessThanOrEqualTo(Boolean value) {
            addCriterion("ip_change <=", value, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeIn(List<Boolean> values) {
            addCriterion("ip_change in", values, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeNotIn(List<Boolean> values) {
            addCriterion("ip_change not in", values, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeBetween(Boolean value1, Boolean value2) {
            addCriterion("ip_change between", value1, value2, "ipChange");
            return (Criteria) this;
        }

        public Criteria andIpChangeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ip_change not between", value1, value2, "ipChange");
            return (Criteria) this;
        }

        public Criteria andSignNumIsNull() {
            addCriterion("sign_num is null");
            return (Criteria) this;
        }

        public Criteria andSignNumIsNotNull() {
            addCriterion("sign_num is not null");
            return (Criteria) this;
        }

        public Criteria andSignNumEqualTo(Integer value) {
            addCriterion("sign_num =", value, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumNotEqualTo(Integer value) {
            addCriterion("sign_num <>", value, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumGreaterThan(Integer value) {
            addCriterion("sign_num >", value, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_num >=", value, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumLessThan(Integer value) {
            addCriterion("sign_num <", value, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumLessThanOrEqualTo(Integer value) {
            addCriterion("sign_num <=", value, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumIn(List<Integer> values) {
            addCriterion("sign_num in", values, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumNotIn(List<Integer> values) {
            addCriterion("sign_num not in", values, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumBetween(Integer value1, Integer value2) {
            addCriterion("sign_num between", value1, value2, "signNum");
            return (Criteria) this;
        }

        public Criteria andSignNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_num not between", value1, value2, "signNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNull() {
            addCriterion("code_type is null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNotNull() {
            addCriterion("code_type is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeEqualTo(Byte value) {
            addCriterion("code_type =", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotEqualTo(Byte value) {
            addCriterion("code_type <>", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThan(Byte value) {
            addCriterion("code_type >", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("code_type >=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThan(Byte value) {
            addCriterion("code_type <", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThanOrEqualTo(Byte value) {
            addCriterion("code_type <=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIn(List<Byte> values) {
            addCriterion("code_type in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotIn(List<Byte> values) {
            addCriterion("code_type not in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeBetween(Byte value1, Byte value2) {
            addCriterion("code_type between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("code_type not between", value1, value2, "codeType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 30 00:15:03 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}