package com.csy.model;

import java.io.Serializable;
import java.util.Date;

public class News implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.cover
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.subtitle
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.state
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.type
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.sort
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.creator
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.modifier
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.modify_time
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_abstract
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String newsAbstract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.cover
     *
     * @return the value of news.cover
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.cover
     *
     * @param cover the value for news.cover
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.subtitle
     *
     * @return the value of news.subtitle
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.subtitle
     *
     * @param subtitle the value for news.subtitle
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.state
     *
     * @return the value of news.state
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.state
     *
     * @param state the value for news.state
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.type
     *
     * @return the value of news.type
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.type
     *
     * @param type the value for news.type
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.sort
     *
     * @return the value of news.sort
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.sort
     *
     * @param sort the value for news.sort
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.creator
     *
     * @return the value of news.creator
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.creator
     *
     * @param creator the value for news.creator
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_time
     *
     * @return the value of news.create_time
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_time
     *
     * @param createTime the value for news.create_time
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.modifier
     *
     * @return the value of news.modifier
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.modifier
     *
     * @param modifier the value for news.modifier
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.modify_time
     *
     * @return the value of news.modify_time
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.modify_time
     *
     * @param modifyTime the value for news.modify_time
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_abstract
     *
     * @return the value of news.news_abstract
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getNewsAbstract() {
        return newsAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_abstract
     *
     * @param newsAbstract the value for news.news_abstract
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setNewsAbstract(String newsAbstract) {
        this.newsAbstract = newsAbstract == null ? null : newsAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated Wed Dec 07 01:21:22 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}