package com.csy.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Rebate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.user_id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.user_code
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.user_name
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.mission_id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Integer missionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.mission_name
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private String missionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.amount
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.earnings
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private BigDecimal earnings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.status
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.create_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Date createTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.creator
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.modify_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Date modifyTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.modifior
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private String modifior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.settle_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Date settleTm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.settle_man
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private String settleMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.type
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.earnings_from
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Integer earningsFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate.import_date
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private Date importDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebate
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.id
     *
     * @return the value of rebate.id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.id
     *
     * @param id the value for rebate.id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.user_id
     *
     * @return the value of rebate.user_id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.user_id
     *
     * @param userId the value for rebate.user_id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.user_code
     *
     * @return the value of rebate.user_code
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.user_code
     *
     * @param userCode the value for rebate.user_code
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.user_name
     *
     * @return the value of rebate.user_name
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.user_name
     *
     * @param userName the value for rebate.user_name
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.mission_id
     *
     * @return the value of rebate.mission_id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Integer getMissionId() {
        return missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.mission_id
     *
     * @param missionId the value for rebate.mission_id
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setMissionId(Integer missionId) {
        this.missionId = missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.mission_name
     *
     * @return the value of rebate.mission_name
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public String getMissionName() {
        return missionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.mission_name
     *
     * @param missionName the value for rebate.mission_name
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setMissionName(String missionName) {
        this.missionName = missionName == null ? null : missionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.amount
     *
     * @return the value of rebate.amount
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.amount
     *
     * @param amount the value for rebate.amount
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.earnings
     *
     * @return the value of rebate.earnings
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public BigDecimal getEarnings() {
        return earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.earnings
     *
     * @param earnings the value for rebate.earnings
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setEarnings(BigDecimal earnings) {
        this.earnings = earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.status
     *
     * @return the value of rebate.status
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.status
     *
     * @param status the value for rebate.status
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.create_tm
     *
     * @return the value of rebate.create_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.create_tm
     *
     * @param createTm the value for rebate.create_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.creator
     *
     * @return the value of rebate.creator
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.creator
     *
     * @param creator the value for rebate.creator
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.modify_tm
     *
     * @return the value of rebate.modify_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Date getModifyTm() {
        return modifyTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.modify_tm
     *
     * @param modifyTm the value for rebate.modify_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setModifyTm(Date modifyTm) {
        this.modifyTm = modifyTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.modifior
     *
     * @return the value of rebate.modifior
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public String getModifior() {
        return modifior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.modifior
     *
     * @param modifior the value for rebate.modifior
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setModifior(String modifior) {
        this.modifior = modifior == null ? null : modifior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.settle_tm
     *
     * @return the value of rebate.settle_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Date getSettleTm() {
        return settleTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.settle_tm
     *
     * @param settleTm the value for rebate.settle_tm
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setSettleTm(Date settleTm) {
        this.settleTm = settleTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.settle_man
     *
     * @return the value of rebate.settle_man
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public String getSettleMan() {
        return settleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.settle_man
     *
     * @param settleMan the value for rebate.settle_man
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setSettleMan(String settleMan) {
        this.settleMan = settleMan == null ? null : settleMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.type
     *
     * @return the value of rebate.type
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.type
     *
     * @param type the value for rebate.type
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.earnings_from
     *
     * @return the value of rebate.earnings_from
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Integer getEarningsFrom() {
        return earningsFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.earnings_from
     *
     * @param earningsFrom the value for rebate.earnings_from
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setEarningsFrom(Integer earningsFrom) {
        this.earningsFrom = earningsFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate.import_date
     *
     * @return the value of rebate.import_date
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public Date getImportDate() {
        return importDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate.import_date
     *
     * @param importDate the value for rebate.import_date
     *
     * @mbg.generated Tue Mar 28 01:18:40 CST 2017
     */
    public void setImportDate(Date importDate) {
        this.importDate = importDate;
    }
}