package com.csy.model;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.rolename
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.roledesc
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String roledesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.rolecode
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String rolecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.creator
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.createtime
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_role.unmodifiable
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Byte unmodifiable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.id
     *
     * @return the value of g_role.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.id
     *
     * @param id the value for g_role.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.rolename
     *
     * @return the value of g_role.rolename
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.rolename
     *
     * @param rolename the value for g_role.rolename
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.roledesc
     *
     * @return the value of g_role.roledesc
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.roledesc
     *
     * @param roledesc the value for g_role.roledesc
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc == null ? null : roledesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.rolecode
     *
     * @return the value of g_role.rolecode
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.rolecode
     *
     * @param rolecode the value for g_role.rolecode
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.creator
     *
     * @return the value of g_role.creator
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.creator
     *
     * @param creator the value for g_role.creator
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.createtime
     *
     * @return the value of g_role.createtime
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.createtime
     *
     * @param createtime the value for g_role.createtime
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_role.unmodifiable
     *
     * @return the value of g_role.unmodifiable
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Byte getUnmodifiable() {
        return unmodifiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_role.unmodifiable
     *
     * @param unmodifiable the value for g_role.unmodifiable
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setUnmodifiable(Byte unmodifiable) {
        this.unmodifiable = unmodifiable;
    }
}