package com.csy.model;

import java.io.Serializable;

public class RoleAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_role_auth.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_role_auth.roleid
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_role_auth.authid
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer authid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_role_auth
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_role_auth.id
     *
     * @return the value of r_role_auth.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_role_auth.id
     *
     * @param id the value for r_role_auth.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_role_auth.roleid
     *
     * @return the value of r_role_auth.roleid
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_role_auth.roleid
     *
     * @param roleid the value for r_role_auth.roleid
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_role_auth.authid
     *
     * @return the value of r_role_auth.authid
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_role_auth.authid
     *
     * @param authid the value for r_role_auth.authid
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setAuthid(Integer authid) {
        this.authid = authid;
    }
}