package com.csy.model;

import java.io.Serializable;
import java.util.Date;

public class Staff implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.code
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.password
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.depart_id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Integer departId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.name
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.leader
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Byte leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.duty
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.status
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.tel
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.mobile
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.id_card
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.email
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.join_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date joinDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.leave_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date leaveDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.login_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date loginDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.upd_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date updDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.city_id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.version
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.type
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.regular_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date regularDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.addlog
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String addlog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.oplog
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String oplog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.gender
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.thirdparty_account
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String thirdpartyAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.creator
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.creattime
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.modifier
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.modifytime
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.disable
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Byte disable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.account
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.unmodifiable
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Byte unmodifiable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.birthday
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.remark
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.login_ip
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_staff.login_times
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private Integer loginTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_staff
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.id
     *
     * @return the value of g_staff.id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.id
     *
     * @param id the value for g_staff.id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.code
     *
     * @return the value of g_staff.code
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.code
     *
     * @param code the value for g_staff.code
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.password
     *
     * @return the value of g_staff.password
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.password
     *
     * @param password the value for g_staff.password
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.depart_id
     *
     * @return the value of g_staff.depart_id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.depart_id
     *
     * @param departId the value for g_staff.depart_id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.name
     *
     * @return the value of g_staff.name
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.name
     *
     * @param name the value for g_staff.name
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.leader
     *
     * @return the value of g_staff.leader
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Byte getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.leader
     *
     * @param leader the value for g_staff.leader
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setLeader(Byte leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.duty
     *
     * @return the value of g_staff.duty
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.duty
     *
     * @param duty the value for g_staff.duty
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.status
     *
     * @return the value of g_staff.status
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.status
     *
     * @param status the value for g_staff.status
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.tel
     *
     * @return the value of g_staff.tel
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.tel
     *
     * @param tel the value for g_staff.tel
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.mobile
     *
     * @return the value of g_staff.mobile
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.mobile
     *
     * @param mobile the value for g_staff.mobile
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.id_card
     *
     * @return the value of g_staff.id_card
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.id_card
     *
     * @param idCard the value for g_staff.id_card
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.email
     *
     * @return the value of g_staff.email
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.email
     *
     * @param email the value for g_staff.email
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.join_dt
     *
     * @return the value of g_staff.join_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getJoinDt() {
        return joinDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.join_dt
     *
     * @param joinDt the value for g_staff.join_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setJoinDt(Date joinDt) {
        this.joinDt = joinDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.leave_dt
     *
     * @return the value of g_staff.leave_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getLeaveDt() {
        return leaveDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.leave_dt
     *
     * @param leaveDt the value for g_staff.leave_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setLeaveDt(Date leaveDt) {
        this.leaveDt = leaveDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.login_dt
     *
     * @return the value of g_staff.login_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getLoginDt() {
        return loginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.login_dt
     *
     * @param loginDt the value for g_staff.login_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setLoginDt(Date loginDt) {
        this.loginDt = loginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.upd_dt
     *
     * @return the value of g_staff.upd_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getUpdDt() {
        return updDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.upd_dt
     *
     * @param updDt the value for g_staff.upd_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setUpdDt(Date updDt) {
        this.updDt = updDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.city_id
     *
     * @return the value of g_staff.city_id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.city_id
     *
     * @param cityId the value for g_staff.city_id
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.version
     *
     * @return the value of g_staff.version
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.version
     *
     * @param version the value for g_staff.version
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.type
     *
     * @return the value of g_staff.type
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.type
     *
     * @param type the value for g_staff.type
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.regular_dt
     *
     * @return the value of g_staff.regular_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getRegularDt() {
        return regularDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.regular_dt
     *
     * @param regularDt the value for g_staff.regular_dt
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setRegularDt(Date regularDt) {
        this.regularDt = regularDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.addlog
     *
     * @return the value of g_staff.addlog
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getAddlog() {
        return addlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.addlog
     *
     * @param addlog the value for g_staff.addlog
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setAddlog(String addlog) {
        this.addlog = addlog == null ? null : addlog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.oplog
     *
     * @return the value of g_staff.oplog
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getOplog() {
        return oplog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.oplog
     *
     * @param oplog the value for g_staff.oplog
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setOplog(String oplog) {
        this.oplog = oplog == null ? null : oplog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.gender
     *
     * @return the value of g_staff.gender
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.gender
     *
     * @param gender the value for g_staff.gender
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.thirdparty_account
     *
     * @return the value of g_staff.thirdparty_account
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getThirdpartyAccount() {
        return thirdpartyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.thirdparty_account
     *
     * @param thirdpartyAccount the value for g_staff.thirdparty_account
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setThirdpartyAccount(String thirdpartyAccount) {
        this.thirdpartyAccount = thirdpartyAccount == null ? null : thirdpartyAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.creator
     *
     * @return the value of g_staff.creator
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.creator
     *
     * @param creator the value for g_staff.creator
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.creattime
     *
     * @return the value of g_staff.creattime
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.creattime
     *
     * @param creattime the value for g_staff.creattime
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.modifier
     *
     * @return the value of g_staff.modifier
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.modifier
     *
     * @param modifier the value for g_staff.modifier
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.modifytime
     *
     * @return the value of g_staff.modifytime
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.modifytime
     *
     * @param modifytime the value for g_staff.modifytime
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.disable
     *
     * @return the value of g_staff.disable
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Byte getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.disable
     *
     * @param disable the value for g_staff.disable
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setDisable(Byte disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.account
     *
     * @return the value of g_staff.account
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.account
     *
     * @param account the value for g_staff.account
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.unmodifiable
     *
     * @return the value of g_staff.unmodifiable
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Byte getUnmodifiable() {
        return unmodifiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.unmodifiable
     *
     * @param unmodifiable the value for g_staff.unmodifiable
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setUnmodifiable(Byte unmodifiable) {
        this.unmodifiable = unmodifiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.birthday
     *
     * @return the value of g_staff.birthday
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.birthday
     *
     * @param birthday the value for g_staff.birthday
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.remark
     *
     * @return the value of g_staff.remark
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.remark
     *
     * @param remark the value for g_staff.remark
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.login_ip
     *
     * @return the value of g_staff.login_ip
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.login_ip
     *
     * @param loginIp the value for g_staff.login_ip
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_staff.login_times
     *
     * @return the value of g_staff.login_times
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public Integer getLoginTimes() {
        return loginTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_staff.login_times
     *
     * @param loginTimes the value for g_staff.login_times
     *
     * @mbg.generated Mon Dec 26 00:13:17 CST 2016
     */
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }
}