package com.csy.model;

import java.io.Serializable;

public class SystemConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_name
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_value
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.is_visable
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Byte isVisable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.sort
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.type
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_config
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.id
     *
     * @return the value of system_config.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.id
     *
     * @param id the value for system_config.id
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_name
     *
     * @return the value of system_config.config_name
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_name
     *
     * @param configName the value for system_config.config_name
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.config_value
     *
     * @return the value of system_config.config_value
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.config_value
     *
     * @param configValue the value for system_config.config_value
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.is_visable
     *
     * @return the value of system_config.is_visable
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Byte getIsVisable() {
        return isVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.is_visable
     *
     * @param isVisable the value for system_config.is_visable
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setIsVisable(Byte isVisable) {
        this.isVisable = isVisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.sort
     *
     * @return the value of system_config.sort
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.sort
     *
     * @param sort the value for system_config.sort
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_config.type
     *
     * @return the value of system_config.type
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_config.type
     *
     * @param type the value for system_config.type
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }
}