package com.csy.model;

import java.io.Serializable;
import java.util.Date;

public class UserLevel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.id
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.user_id
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level1
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer level1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level2
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer level2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level3
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer level3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level4
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer level4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.level5
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Integer level5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level.create_tm
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private Date createTm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_level
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.id
     *
     * @return the value of user_level.id
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.id
     *
     * @param id the value for user_level.id
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.user_id
     *
     * @return the value of user_level.user_id
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.user_id
     *
     * @param userId the value for user_level.user_id
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level1
     *
     * @return the value of user_level.level1
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level1
     *
     * @param level1 the value for user_level.level1
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setLevel1(Integer level1) {
        this.level1 = level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level2
     *
     * @return the value of user_level.level2
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getLevel2() {
        return level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level2
     *
     * @param level2 the value for user_level.level2
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setLevel2(Integer level2) {
        this.level2 = level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level3
     *
     * @return the value of user_level.level3
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getLevel3() {
        return level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level3
     *
     * @param level3 the value for user_level.level3
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setLevel3(Integer level3) {
        this.level3 = level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level4
     *
     * @return the value of user_level.level4
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getLevel4() {
        return level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level4
     *
     * @param level4 the value for user_level.level4
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setLevel4(Integer level4) {
        this.level4 = level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.level5
     *
     * @return the value of user_level.level5
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Integer getLevel5() {
        return level5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.level5
     *
     * @param level5 the value for user_level.level5
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setLevel5(Integer level5) {
        this.level5 = level5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level.create_tm
     *
     * @return the value of user_level.create_tm
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public Date getCreateTm() {
        return createTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level.create_tm
     *
     * @param createTm the value for user_level.create_tm
     *
     * @mbg.generated Tue Feb 07 22:12:27 CST 2017
     */
    public void setCreateTm(Date createTm) {
        this.createTm = createTm;
    }
}