package com.csy.dao;

import com.csy.model.Blogroll;
import com.csy.model.BlogrollExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogrollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    long countByExample(BlogrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int deleteByExample(BlogrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int insert(Blogroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int insertSelective(Blogroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    List<Blogroll> selectByExample(BlogrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    Blogroll selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") Blogroll record, @Param("example") BlogrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByExample(@Param("record") Blogroll record, @Param("example") BlogrollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByPrimaryKeySelective(Blogroll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogroll
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByPrimaryKey(Blogroll record);
    
    int updateSort(Blogroll record);

}