package com.csy.dao;

import com.csy.model.Mission;
import com.csy.model.MissionExample;
import com.csy.model.MissionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    long countByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int deleteByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int insert(MissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int insertSelective(MissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    List<MissionWithBLOBs> selectByExampleWithBLOBs(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    List<Mission> selectByExample(MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    MissionWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") MissionWithBLOBs record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MissionWithBLOBs record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int updateByExample(@Param("record") Mission record, @Param("example") MissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int updateByPrimaryKeySelective(MissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mission
     *
     * @mbg.generated Wed Nov 30 00:15:03 CST 2016
     */
    int updateByPrimaryKey(Mission record);
}