package com.csy.dao;

import com.csy.model.NotifyReceiver;
import com.csy.model.NotifyReceiverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotifyReceiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    long countByExample(NotifyReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int deleteByExample(NotifyReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int insert(NotifyReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int insertSelective(NotifyReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    List<NotifyReceiver> selectByExample(NotifyReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    NotifyReceiver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") NotifyReceiver record, @Param("example") NotifyReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int updateByExample(@Param("record") NotifyReceiver record, @Param("example") NotifyReceiverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int updateByPrimaryKeySelective(NotifyReceiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_receiver
     *
     * @mbg.generated Thu Dec 01 23:05:51 CST 2016
     */
    int updateByPrimaryKey(NotifyReceiver record);
}