package com.csy.dao;

import com.csy.model.StaffRole;
import com.csy.model.StaffRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    long countByExample(StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int deleteByExample(StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int insert(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int insertSelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    List<StaffRole> selectByExample(StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    StaffRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") StaffRole record, @Param("example") StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByExample(@Param("record") StaffRole record, @Param("example") StaffRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByPrimaryKeySelective(StaffRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_staff_role
     *
     * @mbg.generated Sun Nov 27 01:44:02 CST 2016
     */
    int updateByPrimaryKey(StaffRole record);
}